from obd import OBDCommand
from obd.protocols import ECU
from obd.decoders import raw_string, percent
from decoders import *

# flake8: noqa

ext_commands = {
#                                          name                       description                          cmd           bytes       decoder              ECU          fast
    'CAN_HEADER_7E0':          OBDCommand("CAN_HEADER_7E0",          "Set CAN module ID to 7E0"          , b"ATSH7E0" ,  0,          raw_string          ,ECU.UNKNOWN, False),
    'CAN_HEADER_7E1':          OBDCommand("CAN_HEADER_7E1",          "Set CAN module ID to 7E1"          , b"ATSH7E1" ,  0,          raw_string          ,ECU.UNKNOWN, False),
    'CAN_HEADER_7E4':          OBDCommand("CAN_HEADER_7E4",          "Set CAN module ID to 7E4"          , b"ATSH7E4" ,  0,          raw_string          ,ECU.UNKNOWN, False),
    'CAN_HEADER_7E7':          OBDCommand("CAN_HEADER_7E7",          "Set CAN module ID to 7E7"          , b"ATSH7E7" ,  0,          raw_string          ,ECU.UNKNOWN, False),

    'CAN_RECEIVE_ADDRESS_7E8': OBDCommand("CAN_RECEIVE_ADDRESS_7E8", "Set the CAN receive address to 7E8"          , b"ATCRA7E8",  0, raw_string          , ECU.UNKNOWN, False),
    'CAN_RECEIVE_ADDRESS_7E9': OBDCommand("CAN_RECEIVE_ADDRESS_7E9", "Set the CAN receive address to 7E9"          , b"ATCRA7E9",  0, raw_string          , ECU.UNKNOWN, False),
    'CAN_RECEIVE_ADDRESS_7EC': OBDCommand("CAN_RECEIVE_ADDRESS_7EC", "Set the CAN receive address to 7EC"          , b"ATCRA7EC",  0, raw_string          , ECU.UNKNOWN, False),
    'CAN_RECEIVE_ADDRESS_7EF': OBDCommand("CAN_RECEIVE_ADDRESS_7EF", "Set the CAN receive address to 7EF"          , b"ATCRA7EF",  0, raw_string          , ECU.UNKNOWN, False),

    'BAT_PACK_CAP_AH_RAW_2018':          OBDCommand("BAT_PACK_CAP_AH_RAW_2018",          "Bat Cap Raw 2018"          , b"2241a3"     ,  0, bat_pack_cap_ah_raw_2018,     ECU.ALL    , False),
    'BAT_PACK_CAP_AH_RAW_2019':          OBDCommand("BAT_PACK_CAP_AH_RAW_2019",          "Bat Cap Raw 2019"          , b"2245f9"     ,  0, bat_pack_cap_ah_raw_2019,     ECU.ALL    , False),
    'BAT_PACK_CAP_AH_EST_2018':          OBDCommand("BAT_PACK_CAP_AH_EST_2018",          "Bat Cap Est"          , b"2241a3"     ,  0, bat_pack_cap_ah_est_2018,     ECU.ALL    , False),
    'BAT_PACK_CAP_AH_EST_2019':          OBDCommand("BAT_PACK_CAP_AH_EST_2019",          "Bat Cap Est"          , b"2245f9"     ,  0, bat_pack_cap_ah_est_2019,     ECU.ALL    , False),
    'BAT_PACK_SOC_DISP':          OBDCommand("BAT_PACK_SOC_DISP",          "Batt % DIC"          , b"228334"     ,  0, bat_pack_soc_disp,     ECU.ALL    , False),
    'BAT_PACK_SOC_RAW_HD':          OBDCommand("BAT_PACK_SOC_RAW_HD",          "SoC Raw HD"          , b"2243af"     ,  0, bat_pack_soc_raw_hd,     ECU.ALL    , False),
    'BAT_PACK_SOC_RAW_LD':          OBDCommand("BAT_PACK_SOC_RAW_LD",          "SoC Raw"          , b"015b"     ,  0, bat_pack_soc_raw_ld_var,     ECU.ALL    , False),
    'BAT_PACK_SOC_RAW_LD2':          OBDCommand("BAT_PACK_SOC_RAW_LD2",          "SoC Raw 2"          , b"222411"     ,  0, bat_pack_soc_raw_ld_var,     ECU.ALL    , False),
    'BAT_PACK_SOC_RAW_LD3':          OBDCommand("BAT_PACK_SOC_RAW_LD3",          "SoC Raw 3"          , b"22432f"     ,  0, bat_pack_soc_raw_ld_var,     ECU.ALL    , False),
    'BAT_PACK_SOC_VAR':          OBDCommand("BAT_PACK_SOC_VAR",          "SoC Var"          , b"22435f"     ,  0, bat_pack_soc_raw_ld_var,     ECU.ALL    , False),
    'BAT_PACK_CURRENT_HD':          OBDCommand("BAT_PACK_CURRENT_HD",          "Batt Amps HD"          , b"2240d4"     ,  0, bat_pack_current_hd,     ECU.ALL    , False),
    'BAT_PACK_NUM_CHARGES':          OBDCommand("BAT_PACK_NUM_CHARGES",          "# Charges"          , b"2243a5"     ,  0, bat_pack_num_charges,     ECU.ALL    , False),
    'BAT_MOD_TEMP_1':          OBDCommand("BAT_MOD_TEMP_1",          "Batt Mod 1"          , b"2240d7"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_2':          OBDCommand("BAT_MOD_TEMP_2",          "Batt Mod 2"          , b"2240d9"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_3':          OBDCommand("BAT_MOD_TEMP_3",          "Batt Mod 3"          , b"2240db"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_4':          OBDCommand("BAT_MOD_TEMP_4",          "Batt Mod 4"          , b"2240dd"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_5':          OBDCommand("BAT_MOD_TEMP_5",          "Batt Mod 5"          , b"2240df"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_6':          OBDCommand("BAT_MOD_TEMP_6",          "Batt Mod 6"          , b"2240e1"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_MAX':          OBDCommand("BAT_MOD_TEMP_MAX",          "Max Batt"          , b"224349"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_MIN':          OBDCommand("BAT_MOD_TEMP_MIN",          "Min Batt"          , b"22434a"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_MOD_TEMP_AVG':          OBDCommand("BAT_MOD_TEMP_AVG",          "Batt Temp Avg"          , b"22434f"     ,  0, bat_mod_temp,     ECU.ALL    , False),
    'BAT_CELL_VOLT_MIN':          OBDCommand("BAT_CELL_VOLT_MIN",          "Min Cell V"          , b"224329"     ,  0, bat_cell_volt_min_max,     ECU.ALL    , False),
    'BAT_CELL_VOLT_MIN_NUM':          OBDCommand("BAT_CELL_VOLT_MIN_NUM",          "Min Cell #"          , b"22432a"     ,  0, bat_cell_volt_min_max_num,     ECU.ALL    , False),
    'BAT_CELL_VOLT_MAX':          OBDCommand("BAT_CELL_VOLT_MAX",          "Max Cell V"          , b"22432b"     ,  0, bat_cell_volt_min_max,     ECU.ALL    , False),
    'BAT_CELL_VOLT_MAX_NUM':          OBDCommand("BAT_CELL_VOLT_MAX_NUM",          "Max Cell #"          , b"22432c"     ,  0, bat_cell_volt_min_max_num,     ECU.ALL    , False),
    'BAT_CELL_VOLT_AVG':          OBDCommand("BAT_CELL_VOLT_AVG",          "Avg Cell"          , b"22c218"     ,  0, bat_cell_volt_avg,     ECU.ALL    , False),
    'BAT_PACK_RESISTANCE':          OBDCommand("BAT_PACK_RESISTANCE",          "Batt Res"          , b"2240e9"     ,  0, bat_pack_resistance,     ECU.ALL    , False),
    'BAT_PACK_VOLT_MIN':          OBDCommand("BAT_PACK_VOLT_MIN",          "Min Batt V"          , b"22433b"     ,  0, bat_pack_volt_min_max,     ECU.ALL    , False),
    'BAT_PACK_VOLT_MAX':          OBDCommand("BAT_PACK_VOLT_MAX",          "Max Batt V"          , b"22433c"     ,  0, bat_pack_volt_min_max,     ECU.ALL    , False),
    'HV_CURRENT_HD':          OBDCommand("HV_CURRENT_HD",          "HV Amps"          , b"222414"     ,  0, hv_current_hd,     ECU.ALL    , False),
    'HV_CURRENT':          OBDCommand("HV_CURRENT",          "HV Amps 2"          , b"224356"     ,  0, hv_current,     ECU.ALL    , False),
    'AMBIENT_AIR_TEMP':          OBDCommand("AMBIENT_AIR_TEMP",          "Amb Air"          , b"220046"     ,  0, ambient_air_temp,     ECU.ALL    , False),
    'BAT_CELL_VOLT_01':          OBDCommand("BAT_CELL_VOLT_01",          "Cell 01"          , b"224181"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_02':          OBDCommand("BAT_CELL_VOLT_02",          "Cell 02"          , b"224182"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_03':          OBDCommand("BAT_CELL_VOLT_03",          "Cell 03"          , b"224183"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_04':          OBDCommand("BAT_CELL_VOLT_04",          "Cell 04"          , b"224184"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_05':          OBDCommand("BAT_CELL_VOLT_05",          "Cell 05"          , b"224185"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_06':          OBDCommand("BAT_CELL_VOLT_06",          "Cell 06"          , b"224186"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_07':          OBDCommand("BAT_CELL_VOLT_07",          "Cell 07"          , b"224187"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_08':          OBDCommand("BAT_CELL_VOLT_08",          "Cell 08"          , b"224188"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_09':          OBDCommand("BAT_CELL_VOLT_09",          "Cell 09"          , b"224189"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_10':          OBDCommand("BAT_CELL_VOLT_10",          "Cell 10"          , b"22418a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_11':          OBDCommand("BAT_CELL_VOLT_11",          "Cell 11"          , b"22418b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_12':          OBDCommand("BAT_CELL_VOLT_12",          "Cell 12"          , b"22418c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_13':          OBDCommand("BAT_CELL_VOLT_13",          "Cell 13"          , b"22418d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_14':          OBDCommand("BAT_CELL_VOLT_14",          "Cell 14"          , b"22418e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_15':          OBDCommand("BAT_CELL_VOLT_15",          "Cell 15"          , b"22418f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_16':          OBDCommand("BAT_CELL_VOLT_16",          "Cell 16"          , b"224190"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_17':          OBDCommand("BAT_CELL_VOLT_17",          "Cell 17"          , b"224191"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_18':          OBDCommand("BAT_CELL_VOLT_18",          "Cell 18"          , b"224192"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_19':          OBDCommand("BAT_CELL_VOLT_19",          "Cell 19"          , b"224193"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_20':          OBDCommand("BAT_CELL_VOLT_20",          "Cell 20"          , b"224194"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_21':          OBDCommand("BAT_CELL_VOLT_21",          "Cell 21"          , b"224195"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_22':          OBDCommand("BAT_CELL_VOLT_22",          "Cell 22"          , b"224196"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_23':          OBDCommand("BAT_CELL_VOLT_23",          "Cell 23"          , b"224197"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_24':          OBDCommand("BAT_CELL_VOLT_24",          "Cell 24"          , b"224198"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_25':          OBDCommand("BAT_CELL_VOLT_25",          "Cell 25"          , b"224199"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_26':          OBDCommand("BAT_CELL_VOLT_26",          "Cell 26"          , b"22419a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_27':          OBDCommand("BAT_CELL_VOLT_27",          "Cell 27"          , b"22419b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_28':          OBDCommand("BAT_CELL_VOLT_28",          "Cell 28"          , b"22419c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_29':          OBDCommand("BAT_CELL_VOLT_29",          "Cell 29"          , b"22419d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_30':          OBDCommand("BAT_CELL_VOLT_30",          "Cell 30"          , b"22419e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_31':          OBDCommand("BAT_CELL_VOLT_31",          "Cell 31"          , b"22419f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_32':          OBDCommand("BAT_CELL_VOLT_32",          "Cell 32"          , b"224200"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_33':          OBDCommand("BAT_CELL_VOLT_33",          "Cell 33"          , b"224201"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_34':          OBDCommand("BAT_CELL_VOLT_34",          "Cell 34"          , b"224202"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_35':          OBDCommand("BAT_CELL_VOLT_35",          "Cell 35"          , b"224203"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_36':          OBDCommand("BAT_CELL_VOLT_36",          "Cell 36"          , b"224204"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_37':          OBDCommand("BAT_CELL_VOLT_37",          "Cell 37"          , b"224205"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_38':          OBDCommand("BAT_CELL_VOLT_38",          "Cell 38"          , b"224206"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_39':          OBDCommand("BAT_CELL_VOLT_39",          "Cell 39"          , b"224207"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_40':          OBDCommand("BAT_CELL_VOLT_40",          "Cell 40"          , b"224208"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_41':          OBDCommand("BAT_CELL_VOLT_41",          "Cell 41"          , b"224209"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_42':          OBDCommand("BAT_CELL_VOLT_42",          "Cell 42"          , b"22420a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_43':          OBDCommand("BAT_CELL_VOLT_43",          "Cell 43"          , b"22420b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_44':          OBDCommand("BAT_CELL_VOLT_44",          "Cell 44"          , b"22420c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_45':          OBDCommand("BAT_CELL_VOLT_45",          "Cell 45"          , b"22420d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_46':          OBDCommand("BAT_CELL_VOLT_46",          "Cell 46"          , b"22420e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_47':          OBDCommand("BAT_CELL_VOLT_47",          "Cell 47"          , b"22420f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_48':          OBDCommand("BAT_CELL_VOLT_48",          "Cell 48"          , b"224210"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_49':          OBDCommand("BAT_CELL_VOLT_49",          "Cell 49"          , b"224211"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_50':          OBDCommand("BAT_CELL_VOLT_50",          "Cell 50"          , b"224212"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_51':          OBDCommand("BAT_CELL_VOLT_51",          "Cell 51"          , b"224213"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_52':          OBDCommand("BAT_CELL_VOLT_52",          "Cell 52"          , b"224214"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_53':          OBDCommand("BAT_CELL_VOLT_53",          "Cell 53"          , b"224215"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_54':          OBDCommand("BAT_CELL_VOLT_54",          "Cell 54"          , b"224216"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_55':          OBDCommand("BAT_CELL_VOLT_55",          "Cell 55"          , b"224217"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_56':          OBDCommand("BAT_CELL_VOLT_56",          "Cell 56"          , b"224218"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_57':          OBDCommand("BAT_CELL_VOLT_57",          "Cell 57"          , b"224219"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_58':          OBDCommand("BAT_CELL_VOLT_58",          "Cell 58"          , b"22421a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_59':          OBDCommand("BAT_CELL_VOLT_59",          "Cell 59"          , b"22421b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_60':          OBDCommand("BAT_CELL_VOLT_60",          "Cell 60"          , b"22421c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_61':          OBDCommand("BAT_CELL_VOLT_61",          "Cell 61"          , b"22421d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_62':          OBDCommand("BAT_CELL_VOLT_62",          "Cell 62"          , b"22421e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_63':          OBDCommand("BAT_CELL_VOLT_63",          "Cell 63"          , b"22421f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_64':          OBDCommand("BAT_CELL_VOLT_64",          "Cell 64"          , b"224220"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_65':          OBDCommand("BAT_CELL_VOLT_65",          "Cell 65"          , b"224221"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_66':          OBDCommand("BAT_CELL_VOLT_66",          "Cell 66"          , b"224222"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_67':          OBDCommand("BAT_CELL_VOLT_67",          "Cell 67"          , b"224223"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_68':          OBDCommand("BAT_CELL_VOLT_68",          "Cell 68"          , b"224224"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_69':          OBDCommand("BAT_CELL_VOLT_69",          "Cell 69"          , b"224225"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_70':          OBDCommand("BAT_CELL_VOLT_70",          "Cell 70"          , b"224226"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_71':          OBDCommand("BAT_CELL_VOLT_71",          "Cell 71"          , b"224227"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_72':          OBDCommand("BAT_CELL_VOLT_72",          "Cell 72"          , b"224228"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_73':          OBDCommand("BAT_CELL_VOLT_73",          "Cell 73"          , b"224229"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_74':          OBDCommand("BAT_CELL_VOLT_74",          "Cell 74"          , b"22422a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_75':          OBDCommand("BAT_CELL_VOLT_75",          "Cell 75"          , b"22422b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_76':          OBDCommand("BAT_CELL_VOLT_76",          "Cell 76"          , b"22422c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_77':          OBDCommand("BAT_CELL_VOLT_77",          "Cell 77"          , b"22422d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_78':          OBDCommand("BAT_CELL_VOLT_78",          "Cell 78"          , b"22422e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_79':          OBDCommand("BAT_CELL_VOLT_79",          "Cell 79"          , b"22422f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_80':          OBDCommand("BAT_CELL_VOLT_80",          "Cell 80"          , b"224230"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_81':          OBDCommand("BAT_CELL_VOLT_81",          "Cell 81"          , b"224231"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_82':          OBDCommand("BAT_CELL_VOLT_82",          "Cell 82"          , b"224232"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_83':          OBDCommand("BAT_CELL_VOLT_83",          "Cell 83"          , b"224233"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_84':          OBDCommand("BAT_CELL_VOLT_84",          "Cell 84"          , b"224234"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_85':          OBDCommand("BAT_CELL_VOLT_85",          "Cell 85"          , b"224235"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_86':          OBDCommand("BAT_CELL_VOLT_86",          "Cell 86"          , b"224236"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_87':          OBDCommand("BAT_CELL_VOLT_87",          "Cell 87"          , b"224237"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_88':          OBDCommand("BAT_CELL_VOLT_88",          "Cell 88"          , b"224238"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_89':          OBDCommand("BAT_CELL_VOLT_89",          "Cell 89"          , b"224239"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_90':          OBDCommand("BAT_CELL_VOLT_90",          "Cell 90"          , b"22423a"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_91':          OBDCommand("BAT_CELL_VOLT_91",          "Cell 91"          , b"22423b"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_92':          OBDCommand("BAT_CELL_VOLT_92",          "Cell 92"          , b"22423c"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_93':          OBDCommand("BAT_CELL_VOLT_93",          "Cell 93"          , b"22423d"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_94':          OBDCommand("BAT_CELL_VOLT_94",          "Cell 94"          , b"22423e"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_95':          OBDCommand("BAT_CELL_VOLT_95",          "Cell 95"          , b"22423f"     ,  0, bat_cell_volt,     ECU.ALL    , False),
    'BAT_CELL_VOLT_96':          OBDCommand("BAT_CELL_VOLT_96",          "Cell 96"          , b"224240"     ,  0, bat_cell_volt,     ECU.ALL    , False),

}
